services:
  - type: web
    name: rutgers-purity-test
    env: node
    nodeVersion: 18
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: DB_NAME
        value: rutgersPurityTest
    plan: free 